ROOT_TITLE = "Boggle!"
ENTER = "Enter"
START = "Start Game"
RESTART = "Restart Game"
WORDS_FOUND = "WORDS FOUND"
BOGGLE = "BOGGLE"
TIME_REMAINED = "Time Remained:"
EMPTY_CLOCK = "--:--"
SCORE = "Score:"
INITIAL_SCORE = "0"
TIME_UP = "Time's up!"
ROW = "row"
COL = "column"
EMPTY = ''
EXIT = 'Quit Game'
HINT = 'Hint'

# messages:
START_GAME_MSG = "let's play Boggle!"
HINT_MSG = "You've got a hint: "
END_GAME_MSG = "Nice game!"
HIGHSCORE_MSG = "Congrats, We have a new highscore!"
NEW_WORD_MSG = "Good job! You found a new word"
STATIC_MSG = "You have already found this word :)"
INVALID_MSG = "Oops.. Invalid word"
RESTART_MSG = "Are you sure you want to restart?"
EXIT_MSG = "Are you sure you want to quit game?"
END = "You finished the game with the Score of:"
AGAIN = "Do you want to play again?"